version: '2.0'

services:
  profiles-svc:
    depends_on:
      - mongo
    build:
      context: .
    container_name: profiles-svc
    hostname: profiles-svc
    networks:
      - mynet
    environment:
      PROFILES_MONGO_URI: mongodb://mongo:27017
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    networks:
      - mynet
    volumes:
      - ./mongo-data:/data/db

networks:
  mynet:
    driver: bridge